<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Botol extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }
        $this->load->model('botol_model');
    }

    public function index()
    {
        $data['data_botol']=$this->botol_model->ambil_data();
       
		$this->load->view('Parfum/botol',$data);
        
    } 

public function tambah(){
        
        $data=array(
            'action'    =>site_url('Botol/tambah_aksi'),
            'kode_botol'       =>set_value('kode_botol'),
            'nama_botol'      =>set_value('nama_botol'),
            'harga_botol'   =>set_value('harga_botol'),
            
            'button'    =>'Tambah'
            );
        $this->load->view('Parfum/botol_form',$data);
    }

function tambah_aksi(){
        $data=array(
            
            'kode_botol'       =>$this->input->post('kode_botol'),
            'nama_botol'      =>$this->input->post('nama_botol'),
            'harga_botol'   =>$this->input->post('harga_botol')
            
            );
        $this->botol_model->tambah_data($data);
        redirect(site_url('Botol'));
    }

    public function edit($id){
        $mhs=$this->botol_model->ambil_data_id($id);
        $data=array(
            
            'kode_botol'        =>set_value('kode_botol',$mhs->kode_botol),
            'nama_botol'       =>set_value('nama_botol',$mhs->nama_botol),
            'harga_botol'      =>set_value('harga_botol',$mhs->harga_botol),
            
            'action'    =>site_url('Botol/edit_aksi'),
            'button'    =>'Edit'
            
            );
        $this->load->view('Parfum/botol_form',$data);

    }
    
    function edit_aksi(){

            $data=array(
            
            'kode_botol'       =>$this->input->post('kode_botol'),
            'nama_botol'      =>$this->input->post('nama_botol'),
            'harga_botol'   =>$this->input->post('harga_botol')
            
            );
            $id=$this->input->post('kode_botol');
            $this->botol_model->edit_data($id,$data);
            redirect(site_url('Botol'));

    }

    public function delete($id){
        
        $this->botol_model->hapus_data($id);
        redirect(site_url('Botol'));
    
    }

}


/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */