<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Transaksi extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('transaksi_model');
    }

    public function index()
    {
        $data['data_transaksi']=$this->transaksi_model->ambil_data();
       
		$this->load->view('Parfum/transaksi',$data);
        
    } 

    public function tambah(){
        
        $data=array(
            'action'    =>site_url('Transaksi/tambah_aksi'),
            'kode_transaksi'       =>set_value('kode_transaksi'),
            'tanggal'      =>set_value('tanggal'),
            'kode_parfum'   =>set_value('kode_parfum'),
            'kode_botol'   =>set_value('kode_botol'),
            'bibit'   =>set_value('bibit'),
            'campuran'   =>set_value('campuran'),
            'jumlah'   =>set_value('jumlah'),
            'total'   =>set_value('total'),
            
            'button'    =>'Tambah'
            );
        $this->load->view('Parfum/transaksi_form',$data);
    }

function tambah_aksi(){
        $data=array(
            
            
            'tanggal'      =>$this->input->post('tanggal'),
            'kode_parfum'   =>$this->input->post('kode_parfum'),
            'kode_botol'      =>$this->input->post('kode_botol'),
            'bibit'      =>$this->input->post('bibit'),
            'campuran'      =>$this->input->post('campuran'),
            'jumlah'      =>$this->input->post('jumlah'),
            'total'      =>$this->input->post('total')
            
            );
        $this->transaksi_model->tambah_data($data);
        redirect(site_url('Transaksi'));
    }

    public function edit($id){
        $mhs=$this->transaksi_model->ambil_data_id($id);
        $data=array(
            
            'kode_transaksi'        =>set_value('kode_transaksi',$mhs->kode_transaksi),
            'tanggal'       =>set_value('tanggal',$mhs->tanggal),
            'kode_parfum'      =>set_value('kode_parfum',$mhs->kode_parfum),
            'kode_botol'      =>set_value('kode_botol',$mhs->kode_botol),
            'bibit'      =>set_value('bibit',$mhs->bibit),
            'campuran'      =>set_value('campuran',$mhs->campuran),
            'jumlah'      =>set_value('jumlah',$mhs->jumlah),
            'total'      =>set_value('total',$mhs->total),
            
            'action'    =>site_url('Transaksi/edit_aksi'),
            'button'    =>'Edit'
            
            );
        $this->load->view('Parfum/transaksi_form',$data);

    }
    
    function edit_aksi(){

            $data=array(
            
            
            'tanggal'      =>$this->input->post('tanggal'),
            'kode_parfum'   =>$this->input->post('kode_parfum'),
            'kode_botol'      =>$this->input->post('kode_botol'),
            'bibit'      =>$this->input->post('bibit'),
            'campuran'      =>$this->input->post('campuran'),
            'jumlah'      =>$this->input->post('jumlah'),
            'total'      =>$this->input->post('total')
            
            );
            $id=$this->input->post('kode_transaksi');
            $this->transaksi_model->edit_data($id,$data);
            redirect(site_url('Transaksi'));

    }

    public function delete($id){
        
        $this->transaksi_model->hapus_data($id);
        redirect(site_url('Transaksi'));
    
    }

}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */